# syntax = docker/dockerfile:1.4.0

FROM php:8.1-fpm-bullseye

ARG DOCUMENT_ROOT=/var/www
ARG PHP_MODULES=xdebug zip redis pdo pdo_mysql gd intl

RUN \
  apt-get update \
  && apt-get -y upgrade \
  && apt-get install --no-install-recommends -y \
    zsh bash git unzip curl nano netcat iputils-ping pkg-config default-mysql-client \
    libzip-dev zlib1g-dev libicu-dev \
    libfreetype6-dev libjpeg62-turbo-dev libjpeg-dev libpng-dev libwebp-dev

COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin/

SHELL ["/bin/bash", "-c"]

RUN set -ex; \
  docker-php-source extract

# Build/Install PHP-Extensions & PECL Packages
RUN set -ex; \
  for module in ${PHP_MODULES}; do \
    install-php-extensions ${module}; \
  done
